import type { CadernoQuestion } from "./cadernos-data"

export const GRI_2_7_401_QUESTIONS: CadernoQuestion[] = [
  // GRI 401-1 — Novas contratações e desligamentos de empregados
  // SEDE — Mulheres Brancas - Contratações
  {
    id: "gri401-1-sede-mb-30-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-30-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-3050-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-3050-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-50plus-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Mulheres Brancas - Desligamentos
  {
    id: "gri401-1-sede-mb-30-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-30-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-3050-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-3050-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-50plus-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Brancas 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Mulheres Pretas - Contratações
  {
    id: "gri401-1-sede-mp-30-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-30-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-3050-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-3050-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-50plus-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-50plus-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Mulheres Pretas - Desligamentos
  {
    id: "gri401-1-sede-mp-30-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-30-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-3050-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-3050-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-50plus-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mp-50plus-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Pretas 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Mulheres Não-Brancas - Contratações
  {
    id: "gri401-1-sede-mnb-30-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-30-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-3050-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-3050-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-50plus-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Mulheres Não-Brancas - Desligamentos
  {
    id: "gri401-1-sede-mnb-30-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-30-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-3050-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-3050-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-50plus-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-mnb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Mulheres Não-Brancas 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Homens Brancos - Contratações
  {
    id: "gri401-1-sede-hb-30-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-30-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-3050-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-3050-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-50plus-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Homens Brancos - Desligamentos
  {
    id: "gri401-1-sede-hb-30-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-30-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-3050-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-3050-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-50plus-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Brancos 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Homens Não-Brancos - Contratações
  {
    id: "gri401-1-sede-hnb-30-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-30-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-3050-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-3050-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-50plus-num-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // SEDE — Homens Não-Brancos - Desligamentos
  {
    id: "gri401-1-sede-hnb-30-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-30-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-3050-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-3050-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-50plus-num-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-sede-hnb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "SEDE — Homens Não-Brancos 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Mulheres Brancas - Contratações
  {
    id: "gri401-1-oper-mb-30-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-30-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-3050-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-3050-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-50plus-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Mulheres Brancas - Desligamentos
  {
    id: "gri401-1-oper-mb-30-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-30-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-3050-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-3050-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-50plus-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Brancas 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Mulheres Não-Brancas - Contratações
  {
    id: "gri401-1-oper-mnb-30-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-30-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-3050-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-3050-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-50plus-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Mulheres Não-Brancas - Desligamentos
  {
    id: "gri401-1-oper-mnb-30-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-30-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-3050-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-3050-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-50plus-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-mnb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Mulheres Não-Brancas 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Homens Brancos - Contratações
  {
    id: "gri401-1-oper-hb-30-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-30-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-3050-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-3050-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-50plus-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Homens Brancos - Desligamentos
  {
    id: "gri401-1-oper-hb-30-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-30-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-3050-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-3050-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-50plus-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Brancos 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Homens Não-Brancos - Contratações
  {
    id: "gri401-1-oper-hnb-30-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos até 30 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-30-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos até 30 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-3050-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 30 a 50 anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-3050-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 30 a 50 anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-50plus-num-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 50+ anos — Número de novas contratações",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de contratações neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-50plus-pct-contrat",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 50+ anos — Percentual de novas contratações (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver contratações neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  // OPERAÇÕES — Homens Não-Brancos - Desligamentos
  {
    id: "gri401-1-oper-hnb-30-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos até 30 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-30-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos até 30 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-3050-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 30 a 50 anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-3050-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 30 a 50 anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-50plus-num-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 50+ anos — Número de desligamentos",
    type: "number",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros de desligamentos neste grupo, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-1-oper-hnb-50plus-pct-deslig",
    disclosure: "401-1",
    question: "OPERAÇÕES — Homens Não-Brancos 50+ anos — Percentual de desligamentos (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / RAIS / eSocial",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver desligamentos neste grupo, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 401-2 — Benefícios oferecidos a empregados de tempo integral
  {
    id: "gri401-2-seguro-vida",
    disclosure: "401-2",
    question: "A empresa oferece seguro de vida aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-assist-medica",
    disclosure: "401-2",
    question: "A empresa oferece assistência médica aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-invalidez",
    disclosure: "401-2",
    question: "A empresa oferece cobertura por invalidez aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-licenca-maternidade",
    disclosure: "401-2",
    question: "A empresa oferece licença maternidade/paternidade aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-previdencia",
    disclosure: "401-2",
    question: "A empresa oferece previdência privada aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-acoes",
    disclosure: "401-2",
    question: "A empresa oferece participação acionária aos empregados de tempo integral?",
    type: "boolean",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable: 'Os disclosures do GRI 2 e 401 são obrigatórios. Responder "Sim" ou "Não".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-2-outros-beneficios",
    disclosure: "401-2",
    question: "Descreva outros benefícios oferecidos aos empregados de tempo integral",
    type: "text",
    evidence: "Política de benefícios / Convenção coletiva / Portal RH",
    notApplicable:
      "Os disclosures do GRI 2 e 401 são obrigatórios. Liste outros benefícios não mencionados acima, como vale-refeição, vale-transporte, auxílio-creche, etc.",
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 401-3 — Licença maternidade/paternidade
  {
    id: "gri401-3-m-licenca-total",
    disclosure: "401-3",
    question: "Número total de mulheres que tiveram direito à licença maternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-m-licenca-usaram",
    disclosure: "401-3",
    question: "Número total de mulheres que usaram licença maternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-m-retorno-trabalho",
    disclosure: "401-3",
    question: "Número total de mulheres que retornaram ao trabalho após licença maternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-m-retorno-12meses",
    disclosure: "401-3",
    question: "Número total de mulheres que retornaram e permaneceram empregadas 12 meses após o retorno",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-m-taxa-retorno",
    disclosure: "401-3",
    question: "Taxa de retorno ao trabalho de mulheres após licença maternidade (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Calcular: (Número que retornou / Número que usou licença) × 100. Se não houver registros, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-m-taxa-retencao",
    disclosure: "401-3",
    question: "Taxa de retenção de mulheres após licença maternidade (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Calcular: (Número que permaneceu 12 meses / Número que retornou) × 100. Se não houver registros, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-licenca-total",
    disclosure: "401-3",
    question: "Número total de homens que tiveram direito à licença paternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-licenca-usaram",
    disclosure: "401-3",
    question: "Número total de homens que usaram licença paternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-retorno-trabalho",
    disclosure: "401-3",
    question: "Número total de homens que retornaram ao trabalho após licença paternidade",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-retorno-12meses",
    disclosure: "401-3",
    question: "Número total de homens que retornaram e permaneceram empregados 12 meses após o retorno",
    type: "number",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-taxa-retorno",
    disclosure: "401-3",
    question: "Taxa de retorno ao trabalho de homens após licença paternidade (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Calcular: (Número que retornou / Número que usou licença) × 100. Se não houver registros, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri401-3-h-taxa-retencao",
    disclosure: "401-3",
    question: "Taxa de retenção de homens após licença paternidade (%)",
    type: "percentage",
    evidence: "Folha de pagamento / HRIS / Sistema de Benefícios",
    notApplicable:
      'Os disclosures do GRI 2 e 401 são obrigatórios. Calcular: (Número que permaneceu 12 meses / Número que retornou) × 100. Se não houver registros, preencher com "0 %".',
    frameworkGRI: "GRI",
    subFrameworkGRI: "401",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
]

export const gri27401Questions = GRI_2_7_401_QUESTIONS
export const gri27And401Questions = GRI_2_7_401_QUESTIONS
