import type { CadernoQuestion } from "./cadernos-data"

export const GRI_402_409_QUESTIONS: CadernoQuestion[] = [
  // GRI 402-1 — Relações trabalhistas e negociação coletiva
  {
    id: "gri402-1-pct-cobertos",
    disclosure: "402-1",
    question: "Percentual de empregados cobertos por convenções ou acordos coletivos (%)",
    type: "percentage",
    evidence: "Registros de RH; acordos coletivos; sindicatos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem cobertura: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-num-cobertos",
    disclosure: "402-1",
    question: "Número total de empregados cobertos por convenções ou acordos coletivos",
    type: "number",
    evidence: "RH; relatórios de relações sindicais; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem cobertura: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-temas-negociacoes",
    disclosure: "402-1",
    question:
      "Descrição dos principais temas abordados nas negociações coletivas (salários, jornada, benefícios, segurança, igualdade)",
    type: "text",
    evidence: "Acordos coletivos; atas de negociação",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-politica-negociacao",
    disclosure: "402-1",
    question: "Existência de política formal para negociação com sindicatos e representantes de empregados",
    type: "text",
    evidence: "Política de relações sindicais; regulamentos internos",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-aviso-previo-dias",
    disclosure: "402-1",
    question: "Tempo mínimo de aviso prévio para mudanças operacionais significativas (dias)",
    type: "number",
    evidence: "Políticas internas; acordos coletivos; legislação trabalhista",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-pct-mudancas-aviso",
    disclosure: "402-1",
    question: "Percentual de mudanças operacionais significativas comunicadas com aviso prévio adequado (%)",
    type: "percentage",
    evidence: "Registros de comunicação; atas de reuniões; auditorias internas",
    notApplicable: 'Não aplicável apenas se não houver empregados ou mudanças. Sem ocorrência: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-procedimentos-consulta",
    disclosure: "402-1",
    question: "Descrição dos procedimentos adotados para consulta e comunicação prévia a empregados e sindicatos",
    type: "text",
    evidence: "Políticas de RH; atas; comunicados formais",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-num-reunioes",
    disclosure: "402-1",
    question: "Número de reuniões realizadas com sindicatos ou representantes de empregados no período",
    type: "number",
    evidence: "Atas de reuniões; registros de pautas",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem reuniões: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-pct-acordos-sst",
    disclosure: "402-1",
    question: "Percentual de acordos coletivos que incluem cláusulas de saúde e segurança (%)",
    type: "percentage",
    evidence: "Acordos coletivos; auditorias; relatórios de SST",
    notApplicable: 'Não aplicável apenas se não houver acordos coletivos. Sem cláusulas: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "gri402-1-mecanismos-dialogo",
    disclosure: "402-1",
    question:
      "Mecanismos internos de diálogo e mediação trabalhista existentes (comissões, ouvidorias, representantes locais)",
    type: "text",
    evidence: "Registros de RH; política de relações de trabalho",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Política de Integridade – Res. ANEEL 1.000/2021 Cap. XI",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "402",
  },
  {
    id: "riscos-trabalhistas",
    disclosure: "–",
    question:
      "Identificação de riscos de greves, passivos trabalhistas, ações judiciais ou custos extraordinários de pessoal com potencial impacto financeiro",
    type: "text",
    evidence: "Relatórios de risco corporativo; base de processos judiciais; matriz de riscos operacionais",
    notApplicable: "Não aplicável apenas se não houver empregados diretos ou acordos coletivos vigentes.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "impactos-financeiros-passivos",
    disclosure: "–",
    question: "Valor total de contingências, indenizações ou provisões trabalhistas relevantes (R$ mil)",
    type: "currency",
    evidence: "Demonstrações financeiras auditadas; notas explicativas; relatórios de auditoria interna",
    notApplicable: "Aplicável quando houver contingências registradas em demonstrações financeiras.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-relacoes-trabalhistas",
    disclosure: "–",
    question:
      "Estrutura de governança e canais de diálogo institucionalizados entre empresa e representantes de empregados",
    type: "text",
    evidence: "Atas de comitês; políticas de relações trabalhistas; relatórios de engajamento sindical",
    notApplicable: "Aplicável a organizações com empregados próprios e acordos coletivos.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "metas-cobertura-negociacao",
    disclosure: "–",
    question: "Percentual de empregados cobertos por acordos ou convenções coletivas em relação ao total de empregados",
    type: "percentage",
    evidence: "Relatórios de RH; bases de dados de relações sindicais; indicadores de diversidade e emprego",
    notApplicable: "Não aplicável se a organização não possuir empregados formais.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 403 — Sistema de gestão de saúde e segurança ocupacional
  {
    id: "gri403-1-sistema-sst",
    disclosure: "403-1",
    question:
      "Descrever políticas, abrangência e responsabilidades do sistema de SST; complementar com reporte de governança e integração ao sistema de riscos corporativos",
    type: "text",
    evidence: "Política e manual de SST; organograma; certificados ISO 45001",
    notApplicable: "Não aplicável apenas se não houver empregados próprios ou terceiros sob gestão direta.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-2-identificacao-perigos",
    disclosure: "403-2",
    question:
      "Descrever procedimentos de identificação e investigação de incidentes; complementar com análise de impactos financeiros ou operacionais decorrentes",
    type: "text",
    evidence: "Relatórios de incidentes; matriz de risco; planos de mitigação",
    notApplicable: "Não aplicável se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-3-saude-ocupacional",
    disclosure: "403-3",
    question:
      "Descrever programas de saúde ocupacional; incluir custos e provisões relacionadas à saúde ocupacional conforme IFRS S1 (R$ mil)",
    type: "currency",
    evidence: "Programas de saúde; relatórios médicos; notas explicativas",
    notApplicable: "Não aplicável apenas se não houver empregados próprios.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-4-participacao-trabalhadores",
    disclosure: "403-4",
    question: "Descrever mecanismos de participação e consulta dos trabalhadores em SST",
    type: "text",
    evidence: "Atas de CIPA; registros de reuniões; comunicações internas",
    notApplicable: "Não aplicável se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-5-treinamento-sst",
    disclosure: "403-5",
    question:
      "Percentual de empregados que receberam treinamento periódico de SST; complementar com metas de redução de acidentes",
    type: "percentage",
    evidence: "Registros de treinamento; listas de presença; planos de capacitação",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-6-promocao-saude",
    disclosure: "403-6",
    question: "Descrever programas de saúde física e mental; incluir percentual de empregados com acesso",
    type: "percentage",
    evidence: "Programas de saúde e bem-estar; relatórios de RH",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-7-prevencao-mitigacao",
    disclosure: "403-7",
    question: "Descrever medidas preventivas aplicadas a fornecedores e terceiros",
    type: "text",
    evidence: "Avaliações de risco de fornecedores; cláusulas contratuais",
    notApplicable: "Não aplicável se não houver interface operacional com terceiros.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-8-cobertura-sst",
    disclosure: "403-8",
    question: "Percentual de empregados e terceiros cobertos por sistema de gestão de SST",
    type: "percentage",
    evidence: "Cadastro de empregados; relatórios de certificação; auditorias internas",
    notApplicable: "Não aplicável se não houver empregados ou terceiros sob gestão.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Segurança do Trabalho – Resolução ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-9-taxa-frequencia",
    disclosure: "403-9",
    question: "Taxa de frequência de lesões com afastamento (por milhão de horas-homem)",
    type: "number",
    evidence: "Registros de acidentes; CAT; relatórios de SST",
    notApplicable: "Não aplicável se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes de Trabalho (ANEEL / MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-9-taxa-gravidade",
    disclosure: "403-9",
    question: "Taxa de gravidade de lesões com afastamento (por milhão de horas-homem)",
    type: "number",
    evidence: "Registros de acidentes; CAT; relatórios de SST",
    notApplicable: "Não aplicável se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes de Trabalho (ANEEL / MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "aneel-acidentes-com-afastamento",
    disclosure: "–",
    question: "Número de acidentes de trabalho (com afastamento)",
    type: "number",
    evidence: "CAT; Relatórios de SST; Fiscalização ANEEL",
    notApplicable: "Não aplicável apenas se a empresa não for regulada pela ANEEL.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
  },
  {
    id: "aneel-acidentes-sem-afastamento",
    disclosure: "–",
    question: "Número de acidentes de trabalho (sem afastamento)",
    type: "number",
    evidence: "CAT; Relatórios de SST; Fiscalização ANEEL",
    notApplicable: "Não aplicável apenas se a empresa não for regulada pela ANEEL.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
  },
  {
    id: "aneel-taxa-fa",
    disclosure: "–",
    question: "Taxa de frequência de acidentes (FA)",
    type: "number",
    evidence: "Relatórios de SST; Base de horas trabalhadas; Fiscalização ANEEL",
    notApplicable: "Não aplicável apenas se a empresa não for regulada pela ANEEL.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
  },
  {
    id: "aneel-taxa-ga",
    disclosure: "–",
    question: "Taxa de gravidade de acidentes (GA)",
    type: "number",
    evidence: "Relatórios de SST; CAT; Relatórios de Fiscalização ANEEL",
    notApplicable: "Não aplicável apenas se a empresa não for regulada pela ANEEL.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
  },
  {
    id: "aneel-pct-treinados-seguranca",
    disclosure: "–",
    question: "Percentual de empregados treinados em segurança do trabalho",
    type: "percentage",
    evidence: "Registros de Treinamento; Relatórios de Capacitação; Auditorias Internas",
    notApplicable: "Não aplicável apenas se a empresa não for regulada pela ANEEL.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
  },
  {
    id: "gri403-10-doencas-ocupacionais-num",
    disclosure: "403-10",
    question: "Número total de casos confirmados de doenças ocupacionais no período",
    type: "number",
    evidence: "Registros de saúde ocupacional; relatórios de PCMSO e PGR",
    notApplicable: "Não aplicável se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes de Trabalho (ANEEL / MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "gri403-10-taxa-incidencia",
    disclosure: "403-10",
    question:
      "Taxa de incidência de doenças ocupacionais (casos/1.000 empregados); complementar com provisões ou custos associados (IFRS S1)",
    type: "number",
    evidence: "Registros de saúde ocupacional; relatórios de PCMSO e PGR",
    notApplicable: "Não aplicável se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes de Trabalho (ANEEL / MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "403",
  },
  {
    id: "impacto-financeiro-acidentes",
    disclosure: "–",
    question:
      "Valor total de contingências, indenizações, seguros e custos de afastamentos relacionados a acidentes (R$ mil)",
    type: "currency",
    evidence: "Demonstrações financeiras; relatórios de RH e jurídico; notas explicativas",
    notApplicable: "Aplicável quando houver contingências ou custos registrados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "impacto-financeiro-doencas",
    disclosure: "–",
    question:
      "Valor total de contingências, indenizações, seguros e custos de afastamentos relacionados a doenças ocupacionais (R$ mil)",
    type: "currency",
    evidence: "Demonstrações financeiras; relatórios de RH e jurídico; notas explicativas",
    notApplicable: "Aplicável quando houver contingências ou custos registrados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Fiscalização de Segurança – Indicadores de Acidentes (ANEEL/MTE)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-sst",
    disclosure: "–",
    question: "Estrutura de governança, papéis e responsabilidades na gestão de SST e reporte à alta administração",
    type: "text",
    evidence: "Atas de comitês de segurança; organogramas; políticas e procedimentos de SST",
    notApplicable: "Aplicável a todas as organizações com empregados próprios ou terceiros sob gestão direta.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 404 — Treinamento de empregados
  {
    id: "gri404-1-num-treinados",
    disclosure: "404-1",
    question:
      "Número total de empregados que participaram de treinamentos obrigatórios e programas corporativos (operacionais, SST, integridade, diversidade e ambientais).",
    type: "number",
    evidence: "Relatórios de RH; planilhas de treinamento; eSocial",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem treinamentos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-pct-treinados",
    disclosure: "404-1",
    question:
      "Percentual de empregados e terceirizados que participaram de treinamentos obrigatórios ou relacionados à atividade da empresa (segurança do trabalho, integridade, ética, governança, meio ambiente, atendimento, operação ou manutenção). (%)",
    type: "percentage",
    evidence: "Relatórios de RH; certificados de participação",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem treinamento: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas",
    disclosure: "404-1",
    question:
      "Média anual de horas de treinamento por empregado, considerando apenas capacitações obrigatórias ou vinculadas às atividades da empresa (segurança, operação, manutenção, governança, ética, meio ambiente, atendimento e integridade).",
    type: "number",
    evidence: "Relatórios de RH; dashboards internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-homens",
    disclosure: "404-1",
    question:
      "Média anual de horas de treinamento de Homens. Incluindo somente capacitações obrigatórias ou relacionadas às funções institucionais e reguladas.",
    type: "number",
    evidence: "Relatórios de RH; RAIS; planilhas de treinamento",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-mulheres",
    disclosure: "404-1",
    question:
      "Média anual de horas de treinamento de Mulheres. Incluindo somente capacitações obrigatórias ou relacionadas às funções institucionais e reguladas.",
    type: "number",
    evidence: "Relatórios de RH; RAIS; planilhas de treinamento",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-diretoria",
    disclosure: "404-1",
    question: "Média anual de horas de treinamento por categoria funcional: diretoria",
    type: "number",
    evidence: "Planilhas de RH; relatórios internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-gerencia",
    disclosure: "404-1",
    question: "Média anual de horas de treinamento por categoria funcional: gerência",
    type: "number",
    evidence: "Planilhas de RH; relatórios internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-proprios",
    disclosure: "404-1",
    question: "Média anual de horas de treinamento por categoria funcional: Colaboradores Próprios",
    type: "number",
    evidence: "Planilhas de RH; relatórios internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-1-media-horas-terceiros",
    disclosure: "404-1",
    question: "Média anual de horas de treinamento por categoria funcional: Colaboradores Terceiros",
    type: "number",
    evidence: "Planilhas de RH; relatórios internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "impacto-financeiro-capacitacao",
    disclosure: "–",
    question:
      "Valor total investido em programas de treinamento e capacitação corporativa, incluindo custos com instrutores, horas internas, plataformas LMS, contratos de parceiros e certificações obrigatórias (ANEEL, NRs, ISO, ESG e integridade).",
    type: "currency",
    evidence: "Relatórios financeiros; planilhas orçamentárias; indicadores de ROI de treinamento",
    notApplicable: "Aplicável quando houver registro financeiro do investimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-capacitacao",
    disclosure: "–",
    question:
      "Estrutura de governança e reporte à alta administração sobre metas e resultados de desenvolvimento de pessoas",
    type: "text",
    evidence: "Atas de comitês de pessoas; políticas de capacitação; organogramas",
    notApplicable: "Aplicável a organizações com estrutura formal de gestão de pessoas.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri404-2-programas-desenvolvimento",
    disclosure: "404-2",
    question:
      "Descrever os programas formais de capacitação, sucessão e desenvolvimento de carreira (PDI, sucessão técnica, liderança, integração de novos colaboradores, pré-aposentadoria, recolocação).",
    type: "text",
    evidence: "Políticas de RH; relatórios de treinamento; planos de sucessão",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-2-num-programas",
    disclosure: "404-2",
    question: "Número total de programas de desenvolvimento e transição ativos no período.",
    type: "number",
    evidence: "Planilhas de RH; relatórios de capacitação",
    notApplicable: 'Aplicável a todas as organizações com empregados. Se não houver programas, registrar "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-2-pct-cobertos",
    disclosure: "404-2",
    question: "Percentual de empregados cobertos por programas de capacitação e desenvolvimento profissional.",
    type: "percentage",
    evidence: "Relatórios de RH; planilhas de treinamento",
    notApplicable: 'Aplicável a todas as organizações com empregados. Se não houver programas, registrar "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "investimento-programas",
    disclosure: "–",
    question: "Valor total investido em programas de capacitação, desenvolvimento e transição de carreira (R$ mil).",
    type: "text",
    evidence: "Relatórios de RH; políticas internas",
    notApplicable: 'Aplicável a todas as organizações com empregados. Se não houver investimento, registrar "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Capacitação e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "gri404-3-pct-avaliados",
    disclosure: "404-3",
    question: "Percentual de empregados que receberam avaliação formal de desempenho (%)",
    type: "percentage",
    evidence: "Relatórios de RH; sistemas de gestão de desempenho",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-3-pct-mulheres-avaliadas",
    disclosure: "404-3",
    question: "Percentual de mulheres avaliadas (%)",
    type: "percentage",
    evidence: "RH; relatórios de gestão de pessoas",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados Mulheres. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-3-pct-homens-avaliados",
    disclosure: "404-3",
    question: "Percentual de homens avaliados (%)",
    type: "percentage",
    evidence: "RH; relatórios de gestão de pessoas",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados Homens. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-3-pct-lideres-avaliados",
    disclosure: "404-3",
    question: "Percentual de líderes (chefias/gestores) avaliados (%)",
    type: "percentage",
    evidence: "Relatórios de RH; dashboards de desempenho",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-3-metodologia",
    disclosure: "404-3",
    question: "Descrição da metodologia utilizada para avaliação de desempenho",
    type: "text",
    evidence: "Relatórios de RH; documentos de metodologia",
    notApplicable:
      'Aplicável a todas as organizações com empregados. Caso não exista processo formal, preencher "Sem processo de avaliação implementado" e indicar planos ou prazos para implantação.',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "gri404-3-periodicidade",
    disclosure: "404-3",
    question: "Periodicidade das avaliações (anual, semestral etc.)",
    type: "text",
    evidence: "Política de gestão de desempenho",
    notApplicable:
      'Aplicável a todas as organizações com empregados. Caso não exista processo formal, preencher "Sem processo de avaliação implementado" e indicar planos ou prazos para implantação.',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Gestão de Pessoas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "404",
  },
  {
    id: "governanca-desempenho",
    disclosure: "–",
    question:
      "Estrutura de governança e reporte à alta administração sobre metas e resultados de desenvolvimento de pessoas",
    type: "text",
    evidence: "Atas de comitês de pessoas; políticas de capacitação; organogramas",
    notApplicable:
      "Aplicável a todas as organizações com empregados. Se a estrutura de gestão de pessoas não estiver formalizada, descrever o responsável direto e o fluxo de reporte à alta administração",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "impacto-financeiro-desempenho",
    disclosure: "–",
    question:
      "Valor total de despesas e provisões associadas a programas de bônus, metas de desempenho e incentivos atrelados à produtividade (R$ mil)",
    type: "currency",
    evidence: "Relatórios financeiros; notas explicativas; políticas de remuneração variável",
    notApplicable: "Aplicável quando houver programas de remuneração variável vinculados a desempenho.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 405 — Diversidade em órgãos de governança e entre empregados
  {
    id: "gri405-1-num-membros-governanca",
    disclosure: "405-1",
    question: "Número total de membros do órgão de governança (Conselho, Diretoria)",
    type: "number",
    evidence: "Relatórios anuais; atas de assembleia; organogramas",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança formal. Sem membros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-pct-mulheres-governanca",
    disclosure: "405-1",
    question: "Percentual de mulheres em cargos de governança (%)",
    type: "percentage",
    evidence: "Relatórios de governança; formulário de referência",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança. Sem mulheres: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-pct-homens-governanca",
    disclosure: "405-1",
    question: "Percentual de homens em cargos de governança (%)",
    type: "percentage",
    evidence: "Relatórios de governança; formulário de referência",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança. Sem homens: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-pct-negros-governanca",
    disclosure: "405-1",
    question: "Percentual de pessoas negras (pretas + pardas) em cargos de governança (%)",
    type: "percentage",
    evidence: "Relatórios de governança; autodeclarações; RAIS",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança. Sem representação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-pct-indigenas-governanca",
    disclosure: "405-1",
    question: "Percentual de pessoas indígenas em cargos de governança (%)",
    type: "percentage",
    evidence: "Relatórios de governança; RAIS; autodeclarações",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança. Sem representação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-pct-pcd-governanca",
    disclosure: "405-1",
    question: "Percentual de pessoas com deficiência em cargos de governança (%)",
    type: "percentage",
    evidence: "Relatórios de governança; laudos de PCD; cadastros internos",
    notApplicable: 'Não aplicável apenas se a organização não possuir órgão de governança. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-distribuicao-empregados",
    disclosure: "405-1",
    question: "Distribuição dos empregados por gênero e faixa etária",
    type: "text",
    evidence: "RH; relatórios de diversidade; RAIS",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-mb-30",
    disclosure: "405-1",
    question: "Mulheres brancas até 30 anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-mb-3050",
    disclosure: "405-1",
    question: "Mulheres brancas 30 a 50 anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-mb-50plus",
    disclosure: "405-1",
    question: "Mulheres brancas 50+ anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-hp-30",
    disclosure: "405-1",
    question: "Homens pretos até 30 anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-hp-3050",
    disclosure: "405-1",
    question: "Homens pretos 30 a 50 anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-hp-50plus",
    disclosure: "405-1",
    question: "Homens pretos 50+ anos – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-1-nao-binarios",
    disclosure: "405-1",
    question: "Pessoas não binárias – número total de empregados",
    type: "number",
    evidence: "RH; folha de pagamento; RAIS",
    notApplicable:
      'Os disclosures do GRI 2 e 405 são obrigatórios. Não aplicável não se aplica. Se não houver registros, preencher com "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Cap. XI – Gestão de Pessoas e Equidade",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-2-salario-medio-mulheres",
    disclosure: "405-2",
    question: "Salário médio das mulheres (R$/mês)",
    type: "number",
    evidence: "Folha de pagamento; RAIS; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-2-salario-medio-homens",
    disclosure: "405-2",
    question: "Salário médio dos homens (R$/mês)",
    type: "number",
    evidence: "Folha de pagamento; RAIS; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem registros: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-2-proporcao-remuneracao",
    disclosure: "405-2",
    question: "Proporção de remuneração média entre mulheres e homens (%)",
    type: "percentage",
    evidence: "Folha de pagamento; RAIS; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem registros: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-2-proporcao-categoria",
    disclosure: "405-2",
    question: "Proporção de remuneração média entre mulheres e homens por categoria funcional (%)",
    type: "percentage",
    evidence: "Folha de pagamento; RAIS; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem registros: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "gri405-2-politica-equidade",
    disclosure: "405-2",
    question: "Política de equidade salarial e ações de redução de disparidades",
    type: "text",
    evidence: "Política de remuneração; planos de igualdade de gênero e raça",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "405",
  },
  {
    id: "riscos-diversidade",
    disclosure: "–",
    question: "Identificação de riscos reputacionais, de retenção e oportunidades de inovação associados à diversidade",
    type: "text",
    evidence: "Avaliação de riscos corporativos; planos de diversidade e inclusão; relatórios ESG",
    notApplicable: "Aplicável a organizações com políticas ou compromissos públicos de diversidade.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "impacto-financeiro-equidade",
    disclosure: "–",
    question:
      "Valor total de provisões, ajustes ou investimentos realizados para equiparação salarial e programas de equidade (R$ mil)",
    type: "currency",
    evidence: "Relatórios financeiros; notas explicativas; políticas de remuneração",
    notApplicable: "Aplicável quando houver programas de revisão salarial ou metas de equidade com impacto financeiro.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-diversidade",
    disclosure: "–",
    question: "Estrutura de governança, metas e mecanismos de reporte sobre diversidade e inclusão",
    type: "text",
    evidence: "Atas de comitês de pessoas e governança; políticas de diversidade; relatórios de progresso",
    notApplicable: "Aplicável a organizações com estrutura formal de gestão de pessoas e ESG.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Pessoas e Equidade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 406 — Casos de discriminação e ações corretivas tomadas
  {
    id: "gri406-1-politica-discriminacao",
    disclosure: "406-1",
    question: "Existência de política formal de combate à discriminação",
    type: "yesno",
    evidence: "Política de ética e conduta; código de integridade; manual de compliance",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-justificativa",
    disclosure: "406-1",
    question:
      "Justifique caso NÃO tenha política formal de combate à discriminação. Inclua metas de implementação caso tenha.",
    type: "text",
    evidence: null,
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-num-casos",
    disclosure: "406-1",
    question: "Número total de casos de discriminação relatados no período",
    type: "number",
    evidence: "Canal de ética; ouvidoria; registros de RH",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-pct-investigados",
    disclosure: "406-1",
    question: "Percentual de casos investigados (%)",
    type: "percentage",
    evidence: "Relatórios de compliance; registros de apuração",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-pct-corretivas",
    disclosure: "406-1",
    question: "Percentual de casos concluídos com medidas corretivas (%)",
    type: "percentage",
    evidence: "Relatórios de compliance; atas de comitê de ética",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-tipos-medidas",
    disclosure: "406-1",
    question: "Tipos de medidas corretivas aplicadas (advertência, suspensão, desligamento, treinamento, mediação)",
    type: "text",
    evidence: "Relatórios de compliance; registros disciplinares",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-pct-treinados",
    disclosure: "406-1",
    question: "Percentual de empregados cobertos por treinamentos sobre diversidade e não discriminação (%)",
    type: "percentage",
    evidence: "Relatórios de RH; registros de capacitação; material de treinamento",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem treinamento: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-frequencia-treinamentos",
    disclosure: "406-1",
    question: "Frequência de treinamentos (anual, semestral, contínuo)",
    type: "text",
    evidence: "Programa de treinamento; plano anual de capacitação",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-canal-denuncia",
    disclosure: "406-1",
    question: "Existência de canal de denúncia específico para casos de discriminação",
    type: "text",
    evidence: "Política de ouvidoria; portal de ética; comunicações internas",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-pct-cientes",
    disclosure: "406-1",
    question: "Percentual de empregados cientes do canal de denúncia (%)",
    type: "percentage",
    evidence: "Pesquisa interna; relatórios de comunicação; campanhas internas",
    notApplicable: 'Não aplicável apenas se a organização não possuir empregados. Sem resposta: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "gri406-1-protecao-denunciante",
    disclosure: "406-1",
    question: "Descrição dos mecanismos de proteção ao denunciante (anonimato, confidencialidade, não retaliação)",
    type: "text",
    evidence: "Código de conduta; políticas internas; relatório de compliance",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "406",
  },
  {
    id: "impacto-financeiro-discriminacao",
    disclosure: "–",
    question:
      "Valor total de multas, indenizações, custos jurídicos ou provisões relacionadas a casos de discriminação (R$ mil)",
    type: "currency",
    evidence: "Relatórios financeiros; notas explicativas; registros jurídicos; provisões de contingências",
    notApplicable: "Aplicável quando houver registro financeiro de litígios ou penalidades associadas a discriminação.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-etica-discriminacao",
    disclosure: "–",
    question:
      "Estrutura de governança, responsabilidades e mecanismos de reporte ao conselho ou comitês sobre ética, diversidade e conduta",
    type: "text",
    evidence: "Atas de comitês; políticas de governança e integridade; relatórios anuais ESG",
    notApplicable: "Aplicável a organizações com estrutura formal de governança e compliance.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 407 — Liberdade de associação e negociação coletiva
  {
    id: "gri407-1-politica-liberdade",
    disclosure: "407-1",
    question: "Existência de política formal que assegure o direito de associação e negociação coletiva",
    type: "text",
    evidence: "Política de direitos humanos; código de ética; regulamentos internos",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-num-cobertos",
    disclosure: "407-1",
    question: "Número total de empregados cobertos por acordos coletivos",
    type: "number",
    evidence: "RH; relatórios de relações sindicais; eSocial",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem cobertura: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-pct-cobertos",
    disclosure: "407-1",
    question: "Percentual de empregados cobertos por acordos coletivos (%)",
    type: "percentage",
    evidence: "RH; acordos coletivos; sindicatos",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem cobertura: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-num-fornecedores-avaliados",
    disclosure: "407-1",
    question: "Número total de fornecedores avaliados quanto ao respeito à liberdade sindical",
    type: "number",
    evidence: "Planilhas de compras; auditorias de fornecedores",
    notApplicable: 'Não aplicável apenas se não houver cadeia de fornecimento. Sem avaliação: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-pct-fornecedores-avaliados",
    disclosure: "407-1",
    question: "Percentual de fornecedores avaliados quanto à liberdade sindical (%)",
    type: "percentage",
    evidence: "Relatórios de compliance de fornecedores; due diligence ESG",
    notApplicable: 'Não aplicável apenas se não houver cadeia de fornecimento. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-num-casos-violacao",
    disclosure: "407-1",
    question: "Número de casos identificados de violação ao direito de associação e negociação",
    type: "number",
    evidence: "Relatórios de compliance; canal de denúncia; auditorias",
    notApplicable: 'Não aplicável apenas se não houver empregados ou fornecedores. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-medidas-corretivas",
    disclosure: "407-1",
    question: "Medidas corretivas adotadas em casos de violação",
    type: "text",
    evidence: "Relatórios de auditoria; atas de comitês; registros de compliance",
    notApplicable: "Não aplicável apenas se não houver empregados ou fornecedores.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-clausulas-contratuais",
    disclosure: "407-1",
    question: "Existência de cláusulas contratuais que garantam liberdade sindical a fornecedores",
    type: "text",
    evidence: "Contratos de compras; política de fornecedores responsáveis",
    notApplicable: "Não aplicável apenas se não houver fornecedores contratados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-pct-contratos-clausulas",
    disclosure: "407-1",
    question: "Percentual de contratos de fornecimento que incluem cláusulas de liberdade sindical (%)",
    type: "percentage",
    evidence: "Contratos; relatórios de auditoria de fornecedores",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem cláusulas: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Direitos Trabalhistas e Integridade – Res. nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "gri407-1-regioes-risco",
    disclosure: "407-1",
    question: "Regiões ou unidades operacionais com risco identificado (país, estado, setor)",
    type: "text",
    evidence: "Matriz de risco ESG; relatórios de due diligence",
    notApplicable: "Não aplicável apenas se a organização atuar em único país sem fornecedores externos.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "407",
  },
  {
    id: "impacto-financeiro-liberdade",
    disclosure: "–",
    question:
      "Valor total de multas, indenizações, custos jurídicos ou interrupções operacionais associadas a violações de direitos trabalhistas (R$ mil)",
    type: "currency",
    evidence: "Relatórios financeiros; notas explicativas; registros de compliance; autos de infração",
    notApplicable:
      "Aplicável quando houver registros financeiros de contingências relacionadas a violações trabalhistas ou sindicais.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-liberdade-associacao",
    disclosure: "–",
    question:
      "Estrutura de governança, papéis e mecanismos de reporte à alta administração sobre riscos trabalhistas e sindicais",
    type: "text",
    evidence: "Atas de comitês de pessoas e ética; políticas de direitos humanos; organogramas",
    notApplicable: "Aplicável a organizações com empregados próprios ou fornecedores relevantes.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 408 — Trabalho infantil
  {
    id: "gri408-1-politica-trabalho-infantil",
    disclosure: "408-1",
    question: "Existência de política formal de proibição de trabalho infantil",
    type: "yesno",
    evidence: "Código de ética; política de direitos humanos; política de fornecedores",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados ou cadeia de fornecimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-justificativa",
    disclosure: "408-1",
    question:
      "Em caso de NÃO existência de política formal de proibição de trabalho infantil. Justifique e aponte as metas de implementação.",
    type: "text",
    evidence: "Código de ética; política de direitos humanos; política de fornecedores",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados ou cadeia de fornecimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-num-menores-18",
    disclosure: "408-1",
    question: "Número total de empregados menores de 18 anos",
    type: "number",
    evidence: "RH; eSocial; registros trabalhistas",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-pct-menores-18",
    disclosure: "408-1",
    question: "Percentual de empregados menores de 18 anos (%)",
    type: "percentage",
    evidence: "RH; eSocial; auditorias de SST",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-num-fornecedores-avaliados",
    disclosure: "408-1",
    question: "Número total de fornecedores avaliados quanto à ocorrência de trabalho infantil",
    type: "number",
    evidence: "Relatórios de compliance; auditorias de fornecedores; due diligence",
    notApplicable: 'Não aplicável apenas se não houver cadeia de fornecimento. Sem avaliação: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-pct-fornecedores-avaliados",
    disclosure: "408-1",
    question: "Percentual de fornecedores avaliados quanto à ocorrência de trabalho infantil (%)",
    type: "percentage",
    evidence: "Planilhas de compras; relatórios de auditoria ESG",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-num-casos-organizacao",
    disclosure: "408-1",
    question: "Número de casos identificados de trabalho infantil na organização",
    type: "number",
    evidence: "Relatórios de compliance; auditorias internas",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-num-casos-fornecedores",
    disclosure: "408-1",
    question: "Número de casos identificados de trabalho infantil em fornecedores",
    type: "number",
    evidence: "Relatórios de auditoria de fornecedores; due diligence",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-medidas-corretivas",
    disclosure: "408-1",
    question: "Medidas corretivas aplicadas em casos de trabalho infantil identificados",
    type: "text",
    evidence: "Relatórios de compliance; planos de ação corretiva; registros de auditoria",
    notApplicable: "Não aplicável apenas se não houver empregados ou fornecedores.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-pct-casos-resolvidos",
    disclosure: "408-1",
    question: "Percentual de casos resolvidos com medidas corretivas (%)",
    type: "percentage",
    evidence: "Relatórios de auditoria; planos de ação; due diligence",
    notApplicable: 'Não aplicável apenas se não houver empregados ou fornecedores. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-regioes-risco",
    disclosure: "408-1",
    question: "Regiões, setores ou fornecedores com maior risco identificado",
    type: "text",
    evidence: "Matriz de risco ESG; relatórios de auditoria",
    notApplicable: "Não aplicável apenas se a organização atuar em único país e sem fornecedores.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-clausulas-contratuais",
    disclosure: "408-1",
    question:
      "Existência de cláusulas contratuais que proíbam trabalho infantil em fornecedores. Aponte quais. Em caso de NÃO existencia, justifique e aponte as metas de implementação.",
    type: "text",
    evidence: "Contratos; política de compras; código de conduta de fornecedores",
    notApplicable: "Não aplicável apenas se não houver cadeia de fornecimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-pct-contratos-clausulas",
    disclosure: "408-1",
    question: "Percentual de contratos com cláusulas de proibição de trabalho infantil (%)",
    type: "percentage",
    evidence: "Contratos de fornecedores; relatórios de compliance",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem cláusulas: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "gri408-1-programas-prevencao",
    disclosure: "408-1",
    question: "Programas de prevenção e conscientização sobre trabalho infantil (internos e externos)",
    type: "text",
    evidence: "Programas sociais; relatórios de sustentabilidade; comunicação interna",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "408",
  },
  {
    id: "impacto-financeiro-trabalho-infantil",
    disclosure: "–",
    question:
      "Valor total de perdas, multas, provisões ou custos de remediação decorrentes de casos identificados de trabalho infantil (R$ mil)",
    type: "currency",
    evidence:
      "Relatórios financeiros; notas explicativas; registros de compliance; relatórios de auditoria de fornecedores",
    notApplicable: "Aplicável quando houver custos ou provisões relacionados a remediação ou penalidades.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-trabalho-infantil",
    disclosure: "–",
    question:
      "Estrutura de governança, papéis e mecanismos de reporte à alta administração sobre riscos de violação de direitos humanos na cadeia de valor",
    type: "text",
    evidence: "Atas de comitês de ética e sustentabilidade; políticas de direitos humanos; relatórios ESG",
    notApplicable: "Aplicável a organizações com cadeia de suprimentos relevante ou operações em setores de risco.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },

  // GRI 409 — Trabalho forçado ou análogo ao escravo
  {
    id: "gri409-1-politica-trabalho-forcado",
    disclosure: "409-1",
    question:
      "Existência de política formal que proíba o trabalho forçado ou análogo ao escravo. Aponte qual. Em caso de NÃO existencia, justifique e aponte as metas de implementação.",
    type: "text",
    evidence: "Código de ética; política de direitos humanos; política de fornecedores",
    notApplicable: "Não aplicável apenas se a organização não possuir empregados ou cadeia de fornecimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-num-empregados-condicoes",
    disclosure: "409-1",
    question: "Número total de empregados submetidos a condições análogas ao trabalho escravo",
    type: "number",
    evidence: "RH; auditorias internas; denúncias; inspeções do MTE",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-pct-empregados-condicoes",
    disclosure: "409-1",
    question: "Percentual de empregados em condições análogas (%)",
    type: "percentage",
    evidence: "Relatórios de auditoria; eSocial; inspeções",
    notApplicable: 'Não aplicável apenas se não houver empregados. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-num-fornecedores-avaliados",
    disclosure: "409-1",
    question: "Número total de fornecedores avaliados quanto a risco de trabalho forçado",
    type: "number",
    evidence: "Auditorias de fornecedores; relatórios de compliance; due diligence",
    notApplicable: 'Não aplicável apenas se não houver cadeia de fornecimento. Sem avaliação: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-pct-fornecedores-avaliados",
    disclosure: "409-1",
    question: "Percentual de fornecedores avaliados quanto a risco de trabalho forçado (%)",
    type: "percentage",
    evidence: "Auditorias ESG; planilhas de compras; relatórios de due diligence",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem avaliação: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-num-casos-fornecedores",
    disclosure: "409-1",
    question: "Número de casos identificados de trabalho forçado entre fornecedores",
    type: "number",
    evidence: "Relatórios de compliance; auditorias de fornecedores",
    notApplicable: 'Não aplicável apenas se não houver cadeia de fornecimento. Sem casos: "0".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-pct-casos-resolvidos",
    disclosure: "409-1",
    question: "Percentual de casos resolvidos com medidas corretivas (%)",
    type: "percentage",
    evidence: "Planos de ação; relatórios de auditoria; compliance",
    notApplicable: 'Não aplicável apenas se não houver empregados ou fornecedores. Sem casos: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-medidas-corretivas",
    disclosure: "409-1",
    question:
      "Medidas corretivas adotadas em casos identificados (rescisão contratual, denúncia, capacitação, monitoramento)",
    type: "text",
    evidence: "Relatórios de auditoria; planos de ação corretiva",
    notApplicable: "Não aplicável apenas se não houver empregados ou fornecedores.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-clausulas-contratuais",
    disclosure: "409-1",
    question:
      "Existência de cláusulas contratuais que proíbam trabalho forçado em fornecedores. Aponte quais. Em caso de NÃO existencia, justifique e aponte as metas de implementação.",
    type: "text",
    evidence: "Contratos de fornecedores; política de compras; cláusulas de compliance",
    notApplicable: "Não aplicável apenas se não houver cadeia de fornecimento.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-pct-contratos-clausulas",
    disclosure: "409-1",
    question: "Percentual de contratos com cláusulas de proibição de trabalho forçado (%)",
    type: "percentage",
    evidence: "Contratos; auditorias de fornecedores; compliance",
    notApplicable: 'Não aplicável apenas se não houver fornecedores. Sem cláusulas: "0 %".',
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-regioes-risco",
    disclosure: "409-1",
    question: "Regiões, setores ou fornecedores com maior risco identificado",
    type: "text",
    evidence: "Matriz de risco ESG; relatórios de auditoria; due diligence",
    notApplicable: "Não aplicável apenas se a organização atuar em único país e sem fornecedores.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "gri409-1-programas-prevencao",
    disclosure: "409-1",
    question: "Programas de prevenção e capacitação sobre trabalho forçado (internos e na cadeia de valor)",
    type: "text",
    evidence: "Programas sociais; relatórios de sustentabilidade; ações de capacitação",
    notApplicable: "Não aplicável apenas se não houver empregados.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
    frameworkGRI: "GRI",
    subFrameworkGRI: "409",
  },
  {
    id: "impacto-financeiro-trabalho-forcado",
    disclosure: "–",
    question:
      "Valor total de perdas, provisões, multas ou custos de remediação associados a violações identificadas (R$ mil)",
    type: "currency",
    evidence: "Relatórios financeiros; notas explicativas; registros de compliance; relatórios de due diligence",
    notApplicable:
      "Aplicável quando houver custos, penalidades ou provisões relacionadas a violações de direitos humanos.",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
  {
    id: "governanca-trabalho-forcado",
    disclosure: "–",
    question:
      "Estrutura de governança, papéis e mecanismos de reporte à alta administração sobre riscos de trabalho forçado e direitos humanos",
    type: "text",
    evidence: "Atas de comitês de ética e sustentabilidade; políticas de direitos humanos; relatórios ESG",
    notApplicable: "Aplicável a organizações com cadeia de fornecimento relevante ou operações em setores de risco.",
    frameworkANEEL: "Aneel",
    subFrameworkANEEL: "Integridade e Conduta Ética – Res. ANEEL nº 1.000/2021 (Cap. XI)",
    frameworkIFRS: "IFRS / ISSB",
    subFrameworkIFRS: "S1",
  },
]
