import type { DisclosureData } from "@/types/disclosures"

export const GRI_DISCLOSURES: Omit<DisclosureData, "id" | "createdAt" | "updatedAt">[] = [
  // Organização e práticas de relatório (2-1 a 2-6)
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-1",
    title: "Detalhes organizacionais",
    description: "Nome legal, natureza jurídica, localização da sede e países de operação",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-2",
    title: "Entidades incluídas no relatório",
    description: "Lista de entidades incluídas no relatório de sustentabilidade",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-3",
    title: "Período, frequência e ponto de contato",
    description: "Período do relatório, frequência de publicação e ponto de contato",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-4",
    title: "Reformulações de informações",
    description: "Reformulações de informações fornecidas em relatórios anteriores",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-5",
    title: "Verificação externa",
    description: "Política e prática de verificação externa",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-6",
    title: "Atividades, cadeia de valor e outras relações",
    description: "Setor, cadeia de valor e outras relações comerciais relevantes",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  // Adicionar mais 25 disclosures seguindo o mesmo padrão...
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-7",
    title: "Empregados",
    description: "Número total de empregados por gênero, região e tipo de contrato",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "quantitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-8",
    title: "Trabalhadores que não são empregados",
    description: "Número total de trabalhadores que não são empregados",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "quantitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-9",
    title: "Estrutura e composição da governança",
    description: "Estrutura de governança, incluindo comitês do órgão de governança",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-10",
    title: "Nomeação e seleção do mais alto órgão de governança",
    description: "Processo de nomeação e seleção do mais alto órgão de governança",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-11",
    title: "Presidente do mais alto órgão de governança",
    description: "Se o presidente do mais alto órgão de governança também é executivo sênior",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-12",
    title: "Papel do mais alto órgão de governança na supervisão da gestão de impactos",
    description: "Papel do mais alto órgão de governança na supervisão da gestão de impactos",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-13",
    title: "Delegação de responsabilidade pela gestão de impactos",
    description: "Como a responsabilidade pela gestão de impactos é delegada",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-14",
    title: "Papel do mais alto órgão de governança no relatório de sustentabilidade",
    description: "Papel do mais alto órgão de governança no relatório de sustentabilidade",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-15",
    title: "Conflitos de interesse",
    description: "Processos para prevenir e mitigar conflitos de interesse",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-16",
    title: "Comunicação de preocupações críticas",
    description: "Comunicação de preocupações críticas ao mais alto órgão de governança",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-17",
    title: "Conhecimento coletivo do mais alto órgão de governança",
    description: "Medidas para desenvolver e aprimorar o conhecimento coletivo",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-18",
    title: "Avaliação do desempenho do mais alto órgão de governança",
    description: "Processos para avaliar o desempenho do mais alto órgão de governança",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-19",
    title: "Políticas de remuneração",
    description: "Políticas de remuneração para o mais alto órgão de governança e executivos seniores",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-20",
    title: "Processo para determinar a remuneração",
    description: "Processo para determinar a remuneração",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-21",
    title: "Índice de remuneração total anual",
    description: "Índice de remuneração total anual",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "quantitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-22",
    title: "Declaração sobre estratégia de desenvolvimento sustentável",
    description: "Declaração sobre estratégia de desenvolvimento sustentável",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-23",
    title: "Compromissos com políticas",
    description: "Compromissos com políticas",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-24",
    title: "Incorporação de compromissos com políticas",
    description: "Como os compromissos com políticas são incorporados",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-25",
    title: "Processos para remediar impactos negativos",
    description: "Processos para remediar impactos negativos",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-26",
    title: "Mecanismos para buscar aconselhamento e levantar preocupações",
    description: "Mecanismos para buscar aconselhamento e levantar preocupações",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-27",
    title: "Conformidade com leis e regulamentos",
    description: "Conformidade com leis e regulamentos",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-28",
    title: "Associações",
    description: "Associações de membros",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-29",
    title: "Abordagem para engajamento com stakeholders",
    description: "Abordagem para engajamento com stakeholders",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "qualitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
  {
    organizationId: "default-org",
    frameworkId: "GRI",
    standardId: "GRI-2",
    requirementId: "2-30",
    title: "Acordos de negociação coletiva",
    description: "Acordos de negociação coletiva",
    response: "",
    attachments: [],
    status: "not_started",
    dataType: "quantitative",
    reportingPeriod: {
      start: new Date(),
      end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
    assignedTo: "Admin",
    version: 1,
    isValid: false,
    validationErrors: [],
    metrics: [],
  },
]

export function initializeGRIDisclosures() {
  if (typeof window === "undefined") return

  const DISCLOSURES_VERSION = "2.0" // Incrementar quando a estrutura mudar
  const existingDisclosures = localStorage.getItem("esg-disclosures")
  const existingVersion = localStorage.getItem("esg-disclosures-version")

  // Reinicializar se não existir ou se a versão mudou
  if (!existingDisclosures || existingVersion !== DISCLOSURES_VERSION) {
    const disclosuresWithIds = GRI_DISCLOSURES.map((disclosure) => ({
      ...disclosure,
      id: `gri-${disclosure.requirementId}`,
      createdAt: new Date(),
      updatedAt: new Date(),
    }))

    localStorage.setItem("esg-disclosures", JSON.stringify(disclosuresWithIds))
    localStorage.setItem("esg-disclosures-version", DISCLOSURES_VERSION)
    console.log("[v0] Initialized", disclosuresWithIds.length, "GRI disclosures (version", DISCLOSURES_VERSION, ")")
  } else {
    console.log("[v0] Using existing GRI disclosures (version", existingVersion, ")")
  }
}
